title: Path to Peace
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
header:
  title: Fjord
  tagline: Minimal and clean blog theme
  logo_img: images/path-to-peace.png
  bg_img: images/header-bg-ripples.jpg
  has_nav: true
  has_social: trues
footer:
  content: '&copy; All rights reserved.'
  links:
    - text: Made with Stackbit
      url: 'https://www.stackbit.com'
      new_window: true
    - text: Made by Matthew Querzoli
      url: 'https://www.matthewquerzoli.com'
      new_window: true
palette: blue
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
